platform :ios, "7.0"
inhibit_all_warnings!

pod "pop"
pod "Masonry"
pod "AFNetworking","~>2.6.3"
pod "SVProgressHUD"
pod "MBProgressHUD"
pod "Qiniu", "~> 7.0"
pod "UMengAnalytics-NO-IDFA"
pod "UMengSocial"
pod "SDWebImage“
pod "Bugtags","~> 1.1.7"
pod "MWPhotoBrowser"
